# .github/workflows/repo-sync.yml

on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: repo-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "pastaway2/GTMcourse"
          source_branch: "main"
          destination_repo: "https://felixjg1-admin@bitbucket.org/felixjg1/helloworld.git"
          destination_branch: "main"
          #ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          #source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          #destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
